CREATE SEQUENCE seq_medicine START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_stock    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_sale     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
